apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: faq-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: faq-system-backend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5003
        env:
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: faq-system-config
              key: MONGODB_URI
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: faq-system-config
              key: REDIS_URL
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: faq-system-secrets
              key: JWT_SECRET
        - name: GOOGLE_PROJECT_ID
          valueFrom:
            secretKeyRef:
              name: faq-system-secrets
              key: GOOGLE_PROJECT_ID
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: faq-system
spec:
  type: LoadBalancer
  ports:
  - port: 5003
    targetPort: 5003
  selector:
    app: backend 