apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: faq-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: faq-system-frontend:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5173
        env:
        - name: VITE_API_URL
          valueFrom:
            configMapKeyRef:
              name: faq-system-config
              key: VITE_API_URL
        - name: VITE_TINYMCE_API_KEY
          valueFrom:
            secretKeyRef:
              name: faq-system-secrets
              key: TINYMCE_API_KEY
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 5173
          initialDelaySeconds: 30
          periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: faq-system
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5173
  selector:
    app: frontend 